In [2]:
import pandas as pd
import numpy as np
import re


df = pd.read_csv(r"C:\Users\MyBook Hype AMD\Downloads\20240121_shopee_sample_data (1).csv")
df.head(10)

,price_ori,delivery,item_category_detail,specification,title,w_date,link_ori,item_rating,seller_name,idElastic,price_actual,sitename,idHash,total_rating,id,total_sold,pict_link,favorite,timestamp,desc
0,25.80,"KL City, Kuala Lumpur",Shopee | Women's Bags | Shoulder Bags | Should...,Product Specifications Category Shopee Women's...,1081 PU SLING BAG KULIT leather Casual Beg Tan...,2023-04-27,https://shopee.com.my/1081-PU-SLING-BAG-KULIT-...,4.9,qqfwholesale,19ec9fdedd9fe3e14bc652950fc3c423,12.90,shopee,88f051f0a2dcf0d29191e0175b828938,179,88f051f0a2dcf0d29191e0175b828938,179,https://down-my.img.susercontent.com/file/my-1...,Favorite (128,1682553600000,🎉 WELCOME To QQF WHOLESALE \r\n😍 ALL item read...
1,1.41,NaN,Shopee | Home Appliances | Sewing Machines | S...,Product Specifications Category Shopee Home Ap...,Stat Chinese Traditional Frog Buttons Knot Che...,2023-04-27,https://shopee.com.my/Stat-Chinese-Traditional...,5.0,stationery.my,5322309be3b6d9c01d15fa19f5b7ad9a,0.75,shopee,472d22f58af3bb35cf28c6eed7088dc5,17,472d22f58af3bb35cf28c6eed7088dc5,17,https://down-my.img.susercontent.com/file/4147...,Favorite (19,1682553600000,Chinese Traditional Frog Buttons Knot Cheongsa...
2,8.50,"KL City, Kuala Lumpur",Shopee | Women's Bags | Handbags | Set Handbags,Product Specifications Category Shopee Women's...,N09 READY STOCK MYFOOYIN woman handbag set 2in...,2023-04-26,https://shopee.com.my/N09-READY-STOCK-MYFOOYIN...,4.9,fooyin88,7a36765d1e2ca2b6a5414ddfeedfefc3,8.50,shopee,ec6ce64f4b77efb38b6392818959f181,8.1k,ec6ce64f4b77efb38b6392818959f181,8.1k,https://down-my.img.susercontent.com/file/23da...,Favorite (21.5k,1682467200000,READY STOCK\nMEASUREMENT:\nLONG 26CM X HEIGHT ...
3,8.70,NaN,Shopee | Women Clothes | Maternity Wear | Inne...,Product Specifications Category Shopee Women C...,🔥Shocking Sale🔥Cotton Comfort Nursing Bra Brea...,2023-04-26,https://shopee.com.my/%F0%9F%94%A5Shocking-Sal...,4.9,vivi2002,7fc4ab69722e4f788f217b4c044f83eb,8.70,shopee,ef4e0e17fdc7d0125d8609dcc395bc3d,6.5k,ef4e0e17fdc7d0125d8609dcc395bc3d,6.5k,https://down-my.img.susercontent.com/file/df47...,Favorite (3.4k,1682467200000,PRODUCT DESCRIPTION\nMaterial:95%Cotton+5%Span...
4,3999.00,"KL City, Kuala Lumpur",Shopee | Cameras & Drones | DSLR Cameras | DSLRs,Product Specifications Category Shopee Cameras...,Canon EOS 70D 18-55mm IS STM Original+64gb+ext...,2023-04-26,https://shopee.com.my/Canon-EOS-70D-18-55mm-IS...,5.0,xpro.gadget,55608f901f4c5384f884de18227d4298,2739.00,shopee,568c2029fed7d22973ff96d0404a8ff8,10,568c2029fed7d22973ff96d0404a8ff8,10,https://down-my.img.susercontent.com/file/4d3a...,Favorite (132,1682467200000,Canon 70D\nHighlights\nEF-S 18-55mm f/3.5-5.6 ...
5,2950.00,NaN,Shopee | Cameras & Drones | Others | Others,Product Specifications Category Shopee Cameras...,"Atomos Ninja Cast Stand-Alone Switcher, Multiv...",2023-04-26,https://shopee.com.my/Atomos-Ninja-Cast-Stand-...,No ratings yet,cameravalley,12707226efd6bd1243f5e32f7a080999,2950.00,shopee,fe3d2c2c407c9ab3b2890b8e24b0873f,0,fe3d2c2c407c9ab3b2890b8e24b0873f,0,https://down-my.img.susercontent.com/file/sg-1...,NaN,1682467200000,"Atomos Ninja Cast Stand-Alone Switcher, Multiv..."
6,19.00,"KL City, Kuala Lumpur",Shopee | Others | Fengshui & Religious Supplies,Product Specifications Category Shopee Others ...,贺加福 （新）九品莲花大悲咒/30.5cmX30.5cm/正背彩色/莲花纸/1包6色/1色2...,2023-04-26,https://shopee.com.my/%E8%B4%BA%E5%8A%A0%E7%A6...,5.0,hokarhock,160d66bd6367d2eb88c6cd8cbfa8de85,19.00,shopee,de28753a7ba4ec8b40b184a62da006fe,17,de28753a7ba4ec8b40b184a62da006fe,17,https://down-my.img.susercontent.com/file/my-1...,Favorite (11,1682467200000,贺加福\r\n（新）九品莲花大悲咒\r\n30.5cmX30.5cm\r\n一色20张， 一...
7,0.49,NaN,Shopee | Mobile & Accessories | Cases & Covers...,Product Specifications Category Shopee Mobile ...,Mobile Phone Smartphone Powerbank Soft Pouch B...,2023-04-24,https://shopee.com.my/Mobile-Phone-Smartphone-...,4.9,orangetechnology,fb4d23b4ac9927fd6f9225cf0e84254b,0.49,shopee,2111886e473c02ed6705488024b50213,493,2111886e473c02ed6705488024b50213,493,https://down-my.img.susercontent.com/file/5874...,Favorite (219,1682294400000,Mobile Phone Smartphone Power bank Soft Pouch ...
8,11.00,"KL City, Kuala Lumpur",Shopee | Men Clothes | Traditional Wear | Bottoms,Product Specifications Category Shopee Men Clo...,Fashion Men's Sheer Thong Low Rise Stretch G-S...,2023-04-24,https://shopee.com.my/Fashion-Men%27s-Sheer-Th...,5.0,mrbunny.my,f95121639c00abd31d1e49c33428d7ff,5.50,shopee,76a30294ff1350e6d26885efa3188d02,17,76a30294ff1350e6d26885efa3188d02,17,https://down-my.img.susercontent.com/file/7654...,Favorite (34,1682294400000,"Details:* Tag Size: L~2XL, Please make sure th..."
9,599.00,"KL City, Kuala Lumpur",Shopee | Mobile & Accessories | Cool Gadgets |...,Product Specifications Category Shopee Mobile ...,Apple Pencil (2nd Generation) | Shopee Malaysia,2023-04-24,https://shopee.com.my/Apple-Pencil-%282nd-Gene...,4.9,switch_os,d4a021872d337c148690b87e8bd0d8ac,449.00,shopee,b366a4324e4b231e6ab53f6bc35962ff,2.9k,b366a4324e4b231e6ab53f6bc35962ff,2.9k,https://down-my.img.susercontent.com/file/my-1...,Favorite (4.3k,1682294400000,Apple Pencil (2nd generation) delivers pixel-p...

In [3]:
print(df.info())
print("\nMissing Value:\n", df.isnull().sum())

<class 'pandas.DataFrame'>
RangeIndex: 20312 entries, 0 to 20311
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   price_ori             20112 non-null  float64
 1   delivery              6558 non-null   str
 2   item_category_detail  20312 non-null  str
 3   specification         20301 non-null  str
 4   title                 20312 non-null  str
 5   w_date                20312 non-null  str
 6   link_ori              20312 non-null  str
 7   item_rating           20301 non-null  str
 8   seller_name           20301 non-null  str
 9   idElastic             20312 non-null  str
 10  price_actual          20297 non-null  float64
 11  sitename              20312 non-null  str
 12  idHash                20312 non-null  str
 13  total_rating          20301 non-null  str
 14  id                    20312 non-null  str
 15  total_sold            20301 non-null  str
 16  pict_link             20312 non-null  str
 17  favorite              19242 non-null  str
 18  timestamp             20312 non-null  int64
 19  desc                  20312 non-null  str
dtypes: float64(2), int64(1), str(17)
memory usage: 3.1 MB
None

Missing Value:
 price_ori                 200
delivery                13754
item_category_detail        0
specification              11
title                       0
w_date                      0
link_ori                    0
item_rating                11
seller_name                11
idElastic                   0
price_actual               15
sitename                    0
idHash                      0
total_rating               11
id                          0
total_sold                 11
pict_link                   0
favorite                 1070
timestamp                   0
desc                        0
dtype: int64

In [4]:
def clean_number(x):
    if pd.isna(x):
        return 0
    
    x = str(x).lower().strip()
    x = x.replace(',', '.')
    
    try:
        if 'k' in x:
            return float(x.replace('k', '')) * 1000
        elif 'rb' in x:
            return float(x.replace('rb', '')) * 1000
        else:
            return float(x)
    except:
        return 0

In [5]:
df['favorite'].head(20)

0       Favorite (128
1        Favorite (19
2     Favorite (21.5k
3      Favorite (3.4k
4       Favorite (132
5                 NaN
6        Favorite (11
7       Favorite (219
8        Favorite (34
9      Favorite (4.3k
10       Favorite (47
11     Favorite (2.1k
12      Favorite (232
13     Favorite (1.9k
14      Favorite (694
15    Favorite (11.1k
16       Favorite (17
17     Favorite (1.4k
18      Favorite (770
19       Favorite (80
Name: favorite, dtype: str

In [6]:
def clean_favorite_simple(x):
    if pd.isna(x):
        return 0
    
    x = str(x).lower()
    
    import re
    match = re.search(r'[\d.]+', x)
    if not match:
        return 0
    
    num = float(match.group())
    
    if 'k' in x:
        return num * 1000
    else:
        return num

df['favorite'] = df['favorite'].apply(clean_favorite_simple)

In [7]:
df['favorite'].head(20)

0       128.0
1        19.0
2     21500.0
3      3400.0
4       132.0
5         0.0
6        11.0
7       219.0
8        34.0
9      4300.0
10       47.0
11     2100.0
12      232.0
13     1900.0
14      694.0
15    11100.0
16       17.0
17     1400.0
18      770.0
19       80.0
Name: favorite, dtype: float64

In [8]:
# numeric utama
df['total_sold'] = df['total_sold'].apply(clean_number)
df['total_rating'] = df['total_rating'].apply(clean_number)

# favorite (format khusus)
df['favorite'] = df['favorite'].apply(clean_favorite_simple)

# rating
df['item_rating'] = pd.to_numeric(df['item_rating'], errors='coerce')

# harga
df['price_actual'] = pd.to_numeric(df['price_actual'], errors='coerce')
df['price_ori'] = pd.to_numeric(df['price_ori'], errors='coerce')

In [9]:
# harga saling backup
df['price_ori'] = df['price_ori'].fillna(df['price_actual'])
df['price_actual'] = df['price_actual'].fillna(df['price_ori'])

# isi nilai lain
df['total_sold'] = df['total_sold'].fillna(0)
df['favorite'] = df['favorite'].fillna(0)
df['item_rating'] = df['item_rating'].fillna(0)
df['total_rating'] = df['total_rating'].fillna(0)

In [10]:
# revenue
df['revenue'] = df['price_actual'] * df['total_sold']

# discount
df['discount'] = df['price_ori'] - df['price_actual']

# conversion rate (aman dari divide by 0)
df['Sales-to-Favorite Ratio'] = np.where(
    df['favorite'] == 0,
    0,
    df['total_sold'] / df['favorite']
)

In [11]:
df = df.drop(columns=[
    'delivery',
    'link_ori',
    'pict_link',
    'idElastic',
    'idHash'
], errors='ignore')

In [12]:
print(df[['favorite', 'total_sold', 'Sales-to-Favorite Ratio']].head())

print("\nDeskripsi Favorite:")
print(df['favorite'].describe())

print("\nMissing Value Akhir:")
print(df.isnull().sum())

   favorite  total_sold  Sales-to-Favorite Ratio
0     128.0       179.0                 1.398438
1      19.0        17.0                 0.894737
2   21500.0      8100.0                 0.376744
3    3400.0      6500.0                 1.911765
4     132.0        10.0                 0.075758

Deskripsi Favorite:
count    20312.000000
mean      1228.351467
std       3569.903030
min          0.000000
25%         27.000000
50%        174.500000
75%        889.250000
max      96600.000000
Name: favorite, dtype: float64

Missing Value Akhir:
price_ori                   4
item_category_detail        0
specification              11
title                       0
w_date                      0
item_rating                 0
seller_name                11
price_actual                4
sitename                    0
total_rating                0
id                          0
total_sold                  0
favorite                    0
timestamp                   0
desc                        0
revenue                     4
discount                    4
Sales-to-Favorite Ratio     0
dtype: int64

In [13]:
# cek dulu jumlah NaN
print(df[['price_ori', 'price_actual', 'revenue', 'discount']].isnull().sum())

# karena baris bermasalah cuma sedikit, buang baris yang harga masih kosong
df = df.dropna(subset=['price_ori', 'price_actual'])

# hitung ulang revenue dan discount setelah drop NaN
df['revenue'] = df['price_actual'] * df['total_sold']
df['discount'] = df['price_ori'] - df['price_actual']

# kalau ada inf/NaN sisa, amankan
df['revenue'] = df['revenue'].replace([np.inf, -np.inf], 0).fillna(0)
df['discount'] = df['discount'].replace([np.inf, -np.inf], 0).fillna(0)

# rapikan tipe data
df['total_sold'] = df['total_sold'].round(0).astype(int)
df['favorite'] = df['favorite'].round(0).astype(int)
df['total_rating'] = df['total_rating'].round(0).astype(int)
df['revenue'] = df['revenue'].round(0).astype(int)
df['discount'] = df['discount'].round(0).astype(int)

print(df[['price_ori', 'price_actual', 'total_sold', 'favorite', 'revenue', 'discount']].head())

price_ori       4
price_actual    4
revenue         4
discount        4
dtype: int64
   price_ori  price_actual  total_sold  favorite  revenue  discount
0      25.80         12.90         179       128     2309        13
1       1.41          0.75          17        19       13         1
2       8.50          8.50        8100     21500    68850         0
3       8.70          8.70        6500      3400    56550         0
4    3999.00       2739.00          10       132    27390      1260

In [14]:
# ======================
# 8. EXPORT
# ======================
df.to_csv(r"C:\Users\MyBook Hype AMD\Downloads\shopee_clean.csv", index=False)

print("\nData berhasil dibersihkan dan disimpan sebagai 'shopee_clean.csv'")

Data berhasil dibersihkan dan disimpan sebagai 'shopee_clean.csv'

In [ ]:
# load ulang file hasil cleaning
df_check = pd.read_csv(r"C:\Users\MyBook Hype AMD\Downloads\shopee_clean.csv")

print("=== CEK INFO DATA ===")
print(df_check.info())

print("\n=== CEK MISSING VALUE ===")
print(df_check.isnull().sum())

print("\n=== CEK TIPE DATA ===")
print(df_check.dtypes)

print("\n=== CEK NILAI NEGATIF ===")
print("Revenue negatif:", (df_check['revenue'] < 0).sum())
print("Discount negatif:", (df_check['discount'] < 0).sum())

print("\n=== CEK DISTRIBUSI DATA ===")
print(df_check[['total_sold', 'favorite', 'revenue', 'price_actual']].describe())

print("\n=== SAMPLE DATA ===")
print(df_check[['title', 'price_actual', 'total_sold', 'favorite', 'revenue', 'Sales-to-Favorite Ratio']].head(10))

=== CEK INFO DATA ===
<class 'pandas.DataFrame'>
RangeIndex: 20308 entries, 0 to 20307
Data columns (total 18 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   price_ori                20308 non-null  float64
 1   item_category_detail     20308 non-null  str
 2   specification            20297 non-null  str
 3   title                    20308 non-null  str
 4   w_date                   20308 non-null  str
 5   item_rating              20308 non-null  float64
 6   seller_name              20297 non-null  str
 7   price_actual             20308 non-null  float64
 8   sitename                 20308 non-null  str
 9   total_rating             20308 non-null  int64
 10  id                       20308 non-null  str
 11  total_sold               20308 non-null  int64
 12  favorite                 20308 non-null  int64
 13  timestamp                20308 non-null  int64
 14  desc                     20308 non-null  str
 15  revenue                  20308 non-null  int64
 16  discount                 20308 non-null  int64
 17  Sales-to-Favorite Ratio  20308 non-null  float64
dtypes: float64(4), int64(6), str(8)
memory usage: 2.8 MB
None

=== CEK MISSING VALUE ===
price_ori                   0
item_category_detail        0
specification              11
title                       0
w_date                      0
item_rating                 0
seller_name                11
price_actual                0
sitename                    0
total_rating                0
id                          0
total_sold                  0
favorite                    0
timestamp                   0
desc                        0
revenue                     0
discount                    0
Sales-to-Favorite Ratio     0
dtype: int64

=== CEK TIPE DATA ===
price_ori                  float64
item_category_detail           str
specification                  str
title                          str
w_date                         str
item_rating                float64
seller_name                    str
price_actual               float64
sitename                       str
total_rating                 int64
id                             str
total_sold                   int64
favorite                     int64
timestamp                    int64
desc                           str
revenue                      int64
discount                     int64
Sales-to-Favorite Ratio    float64
dtype: object

=== CEK NILAI NEGATIF ===
Revenue negatif: 0
Discount negatif: 0

=== CEK DISTRIBUSI DATA ===
          total_sold      favorite       revenue  price_actual
count   20308.000000  20308.000000  2.030800e+04  2.030800e+04
mean     1560.657278   1228.573813  6.282905e+04  9.887727e+04
std      6190.352739   3570.218681  9.452560e+05  9.923633e+06
min         0.000000      0.000000  0.000000e+00  0.000000e+00
25%        37.000000     27.000000  1.300000e+02  1.000000e+00
50%       204.000000    175.000000  2.086000e+03  1.000000e+01
75%      1000.000000    890.000000  1.913125e+04  6.900000e+01
max    407400.000000  96600.000000  1.110000e+08  1.000000e+09

=== SAMPLE DATA ===
                                               title  price_actual  \
0  1081 PU SLING BAG KULIT leather Casual Beg Tan...         12.90
1  Stat Chinese Traditional Frog Buttons Knot Che...          0.75
2  N09 READY STOCK MYFOOYIN woman handbag set 2in...          8.50
3  🔥Shocking Sale🔥Cotton Comfort Nursing Bra Brea...          8.70
4  Canon EOS 70D 18-55mm IS STM Original+64gb+ext...       2739.00
5  Atomos Ninja Cast Stand-Alone Switcher, Multiv...       2950.00
6  贺加福 （新）九品莲花大悲咒/30.5cmX30.5cm/正背彩色/莲花纸/1包6色/1色2...         19.00
7  Mobile Phone Smartphone Powerbank Soft Pouch B...          0.49
8  Fashion Men's Sheer Thong Low Rise Stretch G-S...          5.50
9    Apple Pencil (2nd Generation) | Shopee Malaysia        449.00

   total_sold  favorite  revenue  Sales-to-Favorite Ratio
0         179       128     2309                 1.398438
1          17        19       13                 0.894737
2        8100     21500    68850                 0.376744
3        6500      3400    56550                 1.911765
4          10       132    27390                 0.075758
5           0         0        0                 0.000000
6          17        11      323                 1.545455
7         493       219      242                 2.251142
8          17        34       94                 0.500000
9        2900      4300  1302100                 0.674419

In [16]:
df.head(10)

,price_ori,item_category_detail,specification,title,w_date,item_rating,seller_name,price_actual,sitename,total_rating,id,total_sold,favorite,timestamp,desc,revenue,discount,Sales-to-Favorite Ratio
0,25.80,Shopee | Women's Bags | Shoulder Bags | Should...,Product Specifications Category Shopee Women's...,1081 PU SLING BAG KULIT leather Casual Beg Tan...,2023-04-27,4.9,qqfwholesale,12.90,shopee,179,88f051f0a2dcf0d29191e0175b828938,179,128,1682553600000,🎉 WELCOME To QQF WHOLESALE \r\n😍 ALL item read...,2309,13,1.398438
1,1.41,Shopee | Home Appliances | Sewing Machines | S...,Product Specifications Category Shopee Home Ap...,Stat Chinese Traditional Frog Buttons Knot Che...,2023-04-27,5.0,stationery.my,0.75,shopee,17,472d22f58af3bb35cf28c6eed7088dc5,17,19,1682553600000,Chinese Traditional Frog Buttons Knot Cheongsa...,13,1,0.894737
2,8.50,Shopee | Women's Bags | Handbags | Set Handbags,Product Specifications Category Shopee Women's...,N09 READY STOCK MYFOOYIN woman handbag set 2in...,2023-04-26,4.9,fooyin88,8.50,shopee,8100,ec6ce64f4b77efb38b6392818959f181,8100,21500,1682467200000,READY STOCK\nMEASUREMENT:\nLONG 26CM X HEIGHT ...,68850,0,0.376744
3,8.70,Shopee | Women Clothes | Maternity Wear | Inne...,Product Specifications Category Shopee Women C...,🔥Shocking Sale🔥Cotton Comfort Nursing Bra Brea...,2023-04-26,4.9,vivi2002,8.70,shopee,6500,ef4e0e17fdc7d0125d8609dcc395bc3d,6500,3400,1682467200000,PRODUCT DESCRIPTION\nMaterial:95%Cotton+5%Span...,56550,0,1.911765
4,3999.00,Shopee | Cameras & Drones | DSLR Cameras | DSLRs,Product Specifications Category Shopee Cameras...,Canon EOS 70D 18-55mm IS STM Original+64gb+ext...,2023-04-26,5.0,xpro.gadget,2739.00,shopee,10,568c2029fed7d22973ff96d0404a8ff8,10,132,1682467200000,Canon 70D\nHighlights\nEF-S 18-55mm f/3.5-5.6 ...,27390,1260,0.075758
5,2950.00,Shopee | Cameras & Drones | Others | Others,Product Specifications Category Shopee Cameras...,"Atomos Ninja Cast Stand-Alone Switcher, Multiv...",2023-04-26,0.0,cameravalley,2950.00,shopee,0,fe3d2c2c407c9ab3b2890b8e24b0873f,0,0,1682467200000,"Atomos Ninja Cast Stand-Alone Switcher, Multiv...",0,0,0.000000
6,19.00,Shopee | Others | Fengshui & Religious Supplies,Product Specifications Category Shopee Others ...,贺加福 （新）九品莲花大悲咒/30.5cmX30.5cm/正背彩色/莲花纸/1包6色/1色2...,2023-04-26,5.0,hokarhock,19.00,shopee,17,de28753a7ba4ec8b40b184a62da006fe,17,11,1682467200000,贺加福\r\n（新）九品莲花大悲咒\r\n30.5cmX30.5cm\r\n一色20张， 一...,323,0,1.545455
7,0.49,Shopee | Mobile & Accessories | Cases & Covers...,Product Specifications Category Shopee Mobile ...,Mobile Phone Smartphone Powerbank Soft Pouch B...,2023-04-24,4.9,orangetechnology,0.49,shopee,493,2111886e473c02ed6705488024b50213,493,219,1682294400000,Mobile Phone Smartphone Power bank Soft Pouch ...,242,0,2.251142
8,11.00,Shopee | Men Clothes | Traditional Wear | Bottoms,Product Specifications Category Shopee Men Clo...,Fashion Men's Sheer Thong Low Rise Stretch G-S...,2023-04-24,5.0,mrbunny.my,5.50,shopee,17,76a30294ff1350e6d26885efa3188d02,17,34,1682294400000,"Details:* Tag Size: L~2XL, Please make sure th...",94,6,0.500000
9,599.00,Shopee | Mobile & Accessories | Cool Gadgets |...,Product Specifications Category Shopee Mobile ...,Apple Pencil (2nd Generation) | Shopee Malaysia,2023-04-24,4.9,switch_os,449.00,shopee,2900,b366a4324e4b231e6ab53f6bc35962ff,2900,4300,1682294400000,Apple Pencil (2nd generation) delivers pixel-p...,1302100,150,0.674419

In [17]:
# total keseluruhan
total_sold_sum = df['total_sold'].sum()
favorite_sum = df['favorite'].sum()

purchase_ratio = total_sold_sum / favorite_sum if favorite_sum != 0 else 0

print("=== TOTAL ===")
print("Total Sold      :", total_sold_sum)
print("Total Favorite  :", favorite_sum)

print("\n=== PURCHASE RATIO ===")
print("Ratio (raw)     :", purchase_ratio)
print("Ratio (%)       : {:.2f}%".format(purchase_ratio * 100))

=== TOTAL ===
Total Sold      : 31693828
Total Favorite  : 24949877

=== PURCHASE RATIO ===
Ratio (raw)     : 1.2702999698154824
Ratio (%)       : 127.03%

In [18]:
# total keseluruhan
total_sold_sum = df['total_sold'].sum()
total_rating_sum = df['total_rating'].sum()

review_rate = total_rating_sum / total_sold_sum if total_sold_sum != 0 else 0

print("=== TOTAL ===")
print("Total Sold     :", total_sold_sum)
print("Total Rating   :", total_rating_sum)

print("\n=== REVIEW RATE ===")
print("Rate (raw)     :", review_rate)
print("Rate (%)       : {:.2f}%".format(review_rate * 100))

=== TOTAL ===
Total Sold     : 31693828
Total Rating   : 31693828

=== REVIEW RATE ===
Rate (raw)     : 1.0
Rate (%)       : 100.00%

In [21]:
# hitung per baris
df['row_review_rate'] = df.apply(
    lambda x: x['total_rating'] / x['total_sold'] if x['total_sold'] != 0 else 0,
    axis=1
)

print("=== RATA-RATA PER PRODUK ===")
print("Mean (raw):", df['row_review_rate'].mean())
print("Mean (%): {:.2f}%".format(df['row_review_rate'].mean() * 100))

=== RATA-RATA PER PRODUK ===
Mean (raw): 0.9671065589915304
Mean (%): 96.71%

In [22]:
ratio_sum = total_rating_sum / total_sold_sum
ratio_avg = df['row_review_rate'].mean()

print("=== PERBANDINGAN ===")
print("SUM method (benar)  : {:.2f}%".format(ratio_sum * 100))
print("AVG method (bias)   : {:.2f}%".format(ratio_avg * 100))

=== PERBANDINGAN ===
SUM method (benar)  : 100.00%
AVG method (bias)   : 96.71%